name: Spec
on:
- push
- pull_request_target

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Set up Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.1'

      - name: Spec
        run: ./spec/mspec/bin/mspec -t ./exe/yarv || true
